require_relative '../config/environment.rb'


jessie = User.new("Jessie")
brian = User.new("brian")
pizza = Recipe.new("pizza")
fries = Recipe.new("fries")
salad = Recipe.new("salad")
oatmeal = Recipe.new("oatmeal")
cookie = Recipe.new("cookie")
brian.add_recipe_card(pizza, "11/7/2018", 10)
brian.add_recipe_card(fries, "11/6/2018", 9)
brian.add_recipe_card(salad, "11/5/2018", 8)
brian.add_recipe_card(oatmeal, "11/4/2018", 7)
brian.add_recipe_card(cookie, "11/3/2018", 6)
curry = Recipe.new("Curry")
burger = Recipe.new("burger")
brian.add_recipe_card(burger, "11/7/2018", 9)
spaghetti = Recipe.new("spaghetti")
fried_rice = Recipe.new("fried rice")
chicken = Ingredient.new("chicken")
jessie.add_recipe_card(burger, "11/6/2018", 8)
jessie.add_recipe_card(spaghetti, "11/5/2018", 9)
jessie.add_recipe_card(fried_rice, "11/4/2018", 7)
curry_recipe = RecipeCard.new("11/7/2018", 10, jessie, curry)
chicken_allergen = Allergen.new(jessie, chicken)
peanut = Ingredient.new("peanut")
jessie.declare_allergen(peanut)
brian.declare_allergen(chicken)
beef = Ingredient.new("beef")
lettuce = Ingredient.new("lettuce")
tomatoe = Ingredient.new("tomatoe")
buns = Ingredient.new("buns")
cheese = Ingredient.new("cheese")
RecipeIngredient.new(burger, beef)
RecipeIngredient.new(burger, lettuce)
RecipeIngredient.new(burger, tomatoe)
RecipeIngredient.new(burger, buns)
RecipeIngredient.new(burger, cheese)
jessie.declare_allergen(beef)
brian.declare_allergen(cheese)
binding.pry
0
